# Generated by Django 5.2.8 on 2025-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(choices=[('user_a', 'Usuário A'), ('user_b', 'Usuário B')], max_length=10, verbose_name='ID do Usuário')),
                ('message', models.TextField(verbose_name='Mensagem do Usuário')),
                ('response', models.TextField(verbose_name='Resposta do Bot')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
    ]
