# Generated by Django 5.2.8 on 2025-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(choices=[('user_a', 'Usuário A'), ('user_b', 'Usuário B')], max_length=10, unique=True),
        ),
    ]
