# Generated by Django 5.2.8 on 2025-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_message_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(choices=[('user_a', 'user_a'), ('user_b', 'user_b')], max_length=10),
        ),
    ]
